workspace = { members = [ "decomposable", "dp", "generating_function","plane-sweep", "probability", "ptr-ds"] }
[package]
name = "discussion"
version = "0.1.0"
style_edition = "2024"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inner = { path = "../inner" }
plane-sweep = { path = "plane-sweep" }
dp = { path = "dp" }
decomposable = { path = "decomposable" }
ptr-ds = { path = "ptr-ds" }
generating_function = { path = "generating_function" }
probability = { path = "probability" }
