[package]
name = "modint"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bin_iter = { path = "../../integer/bin_iter" }
gcd_recip = { path = "../gcd_recip" }
primality = { path = "../primality" }
linear_sieve = { path = "../linear_sieve" }
