[package]
name = "corro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inner = { path = "../inner" }
borrow = { path = "borrow" }
array_rotation = { path = "array_rotation" }
