[package]
name = "foldable_queue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
monoid = { path = "../../ops/monoid" }

[dev-dependencies]
concat-monoid = { path = "../../naive/concat-monoid" }
