name: Cargo test
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Install latest Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          components: miri
          rustflags: '-W warnings'

      - name: Install Zsh
        run: |
          sudo apt-get update
          sudo apt-get install zsh

      - name: Run tests
        run: |
          zsh scripts/ci-test.zsh >> $GITHUB_STEP_SUMMARY
