name: Cargo test
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Install latest Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Run tests
        run: |
          failed=''
          shopt -s globstar
          for f in **/Cargo.toml; do
              cargo test --release --lib --manifest-path=$f ||
                  {
                      failed=t
                      echo '```'
                      echo "$f (--lib)"
                      echo '```'
                  } >> $GITHUB_STEP_SUMMARY
              cargo test --doc --manifest-path=$f ||
                  {
                      failed=t
                      echo '```'
                      echo "$f (--doc)"
                      echo '```'
                  } >> $GITHUB_STEP_SUMMARY
          done
          [[ $failed != t ]]
