name: Cargo test --lib
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cargo-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          path: main

      - name: Install latest Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly

      - name: Install Zsh
        run: |
          sudo apt-get update
          sudo apt-get install zsh

      - name: Run tests
        shell: zsh {0}
        run: |
          zsh scripts/ci-test.zsh --lib >> $GITHUB_STEP_SUMMARY
