name: Push to gh-pages
on:
  push:
    branches:
      - feature/poc2
  workflow_dispatch:

jobs:
  push-to-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: feature/poc2
          path: main

      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Install latest Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Build documents
        run: |
          pwd
          ls
          cargo doc --no-deps --manifest-path=main/nekolib-doc/Cargo.toml
          rm -rf gh-pages/docs
          mv main/nekolib-doc/target/doc gh-pages/docs

      - name: Commit changes
        run: |
          cd gh-pages
          git status
